import type { Metadata } from 'next';

import Provider from '@/providers';
import './globals.css';
import { sans } from '@/utils/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={sans.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
