import { IFollowList } from '@/api/types/follow';

export const followList: IFollowList = [
  {
    _id: '1',
    username: '초록초록 알파카',
    accountname: '@al__1',
    image: '/assets/video.png',
    following: [],
    follower: [],
    followerCount: 10,
    followingCount: 10,
    intro: '초록초록 알파카',
    isfollow: true,
  },
  {
    _id: '2',
    username: '버건디 알파카',
    accountname: '@al__12',
    image: '',
    following: [],
    follower: [],
    followerCount: 20,
    followingCount: 30,
    intro: '버건디 알파카',
    isfollow: true,
  },
  {
    _id: '3',
    username: '코발트블루 알파카',
    accountname: '@al__123',
    image: '/assets/video.png',
    following: [],
    follower: [],
    followerCount: 1000,
    followingCount: 100,
    intro: '코발트블루 알파카',
    isfollow: false,
  },
  {
    _id: '4',
    username: '코발트블루 알파카',
    accountname: '@al__123',
    image: '/assets/video.png',
    following: [],
    follower: [],
    followerCount: 1000,
    followingCount: 100,
    intro: '코발트블루 알파카',
    isfollow: false,
  },
  {
    _id: '5',
    username: '코발트블루 알파카',
    accountname: '@al__123',
    image: '/assets/video.png',
    following: [],
    follower: [],
    followerCount: 1000,
    followingCount: 100,
    intro: '코발트블루 알파카',
    isfollow: false,
  },
  {
    _id: '6',
    username: '코발트블루 알파카',
    accountname: '@al__123',
    image: '/assets/video.png',
    following: [],
    follower: [],
    followerCount: 1000,
    followingCount: 100,
    intro: '코발트블루 알파카',
    isfollow: false,
  },
  {
    _id: '7',
    username: '코발트블루 알파카',
    accountname: '@al__123',
    image: '/assets/video.png',
    following: [],
    follower: [],
    followerCount: 1000,
    followingCount: 100,
    intro: '코발트블루 알파카',
    isfollow: false,
  },
  {
    _id: '8',
    username: '코발트블루 알파카',
    accountname: '@al__123',
    image: '/assets/video.png',
    following: [],
    follower: [],
    followerCount: 1000,
    followingCount: 100,
    intro: '코발트블루 알파카',
    isfollow: false,
  },
  {
    _id: '9',
    username: '코발트블루 알파카',
    accountname: '@al__123',
    image: '/assets/video.png',
    following: [],
    follower: [],
    followerCount: 1000,
    followingCount: 100,
    intro: '코발트블루 알파카',
    isfollow: false,
  },
  {
    _id: '10',
    username: '코발트블루 알파카',
    accountname: '@al__123',
    image: '/assets/video.png',
    following: [],
    follower: [],
    followerCount: 1000,
    followingCount: 100,
    intro: '코발트블루 알파카',
    isfollow: false,
  },
];
