import { IPostList } from '@/api/types/post';

export const postListData: IPostList = {
  posts: [
    {
      id: '1',
      content:
        '한 나의 고독은 둘은 그리도 잊지 차츰 시각에 그 눈물 가실 내 경, 노래를 가로질러 둘로 어찌 내 목란배 사람들의 것이다​ 먹이고 불어오는 가실 하나에 생각이다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: 'al__12345초록초록 알파카',
        accountname: '@al__1',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '2',
      content:
        '이런 자랑처럼 위에 유유히 책상을 까닭입니다. 것을 그리고 밤이 오는 모습 지나고 할 헤는 하나둘 청명한 알리라, 같이 말이 아이들의 고독한 향한 못하는 생을 있다 말했다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '초록색 알파카',
        username: '2초록초록 알파카',
        accountname: 'al__12',
        intro: '안녕 난 알파카2',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '3',
      content:
        '이국 한마디씩 자랑처럼 헤어져 기억해주오 이렇게 지나고 위에 기억해주오 네가 않은 아니 기억해주오 것을 건너 책상을 그러나 향할 소학교 죽고 것은 육체와 우리를 멀리 가시는 써요.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '3',
        username: '3초록파랑알파카',
        accountname: 'al__123',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '4',
      content:
        '하늘을 붉은 이 먼 모두가 그리고 밟고 것 일로도 청춘이 위에 어찌 하지만 사뿐히 침상에서 바다에서 오, 네가 타는 어린 꽃을 꿈꿀 저편으로 밤 사랑했지 다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '4초록빨강 알파카',
        accountname: '@al__1234',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '5',
      content:
        '때​ 오, 별들을 나는 타는 쌓인 갈라놓는 거리가 얼마나 못하는 가로질러 못하는 바다를 걱정도 모습 홀연히 아름다운 이름자 뚝떼어 너도 박명의 왔을까 우는 올라간다. 무덤 있었다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '5초록노랑 알파카',
        accountname: '@al__12345',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '6',
      content:
        '한 나의 고독은 둘은 그리도 잊지 차츰 시각에 그 눈물 가실 내 경, 노래를 가로질러 둘로 어찌 내 목란배 사람들의 것이다​ 먹이고 불어오는 가실 하나에 생각이다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '6초록초록 알파카',
        accountname: '@al__1',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '7',
      content:
        '이런 자랑처럼 위에 유유히 책상을 까닭입니다. 것을 그리고 밤이 오는 모습 지나고 할 헤는 하나둘 청명한 알리라, 같이 말이 아이들의 고독한 향한 못하는 생을 있다 말했다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '초록색 알파카',
        username: '7초록초록 알파카',
        accountname: 'al__12',
        intro: '안녕 난 알파카2',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '8',
      content:
        '이국 한마디씩 자랑처럼 헤어져 기억해주오 이렇게 지나고 위에 기억해주오 네가 않은 아니 기억해주오 것을 건너 책상을 그러나 향할 소학교 죽고 것은 육체와 우리를 멀리 가시는 써요.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '3',
        username: '8초록파랑알파카',
        accountname: 'al__123',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '9',
      content:
        '하늘을 붉은 이 먼 모두가 그리고 밟고 것 일로도 청춘이 위에 어찌 하지만 사뿐히 침상에서 바다에서 오, 네가 타는 어린 꽃을 꿈꿀 저편으로 밤 사랑했지 다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '9초록빨강 알파카',
        accountname: '@al__1234',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '10',
      content:
        '때​ 오, 별들을 나는 타는 쌓인 갈라놓는 거리가 얼마나 못하는 가로질러 못하는 바다를 걱정도 모습 홀연히 아름다운 이름자 뚝떼어 너도 박명의 왔을까 우는 올라간다. 무덤 있었다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '10초록노랑 알파카',
        accountname: '@al__12345',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '11',
      content:
        '한 나의 고독은 둘은 그리도 잊지 차츰 시각에 그 눈물 가실 내 경, 노래를 가로질러 둘로 어찌 내 목란배 사람들의 것이다​ 먹이고 불어오는 가실 하나에 생각이다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '11초록초록 알파카',
        accountname: '@al__1',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '12',
      content:
        '이런 자랑처럼 위에 유유히 책상을 까닭입니다. 것을 그리고 밤이 오는 모습 지나고 할 헤는 하나둘 청명한 알리라, 같이 말이 아이들의 고독한 향한 못하는 생을 있다 말했다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '초록색 알파카',
        username: '12초록초록 알파카',
        accountname: 'al__12',
        intro: '안녕 난 알파카2',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '13',
      content:
        '이국 한마디씩 자랑처럼 헤어져 기억해주오 이렇게 지나고 위에 기억해주오 네가 않은 아니 기억해주오 것을 건너 책상을 그러나 향할 소학교 죽고 것은 육체와 우리를 멀리 가시는 써요.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '3',
        username: '13초록파랑알파카',
        accountname: 'al__123',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '14',
      content:
        '하늘을 붉은 이 먼 모두가 그리고 밟고 것 일로도 청춘이 위에 어찌 하지만 사뿐히 침상에서 바다에서 오, 네가 타는 어린 꽃을 꿈꿀 저편으로 밤 사랑했지 다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '14초록빨강 알파카',
        accountname: '@al__1234',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '15',
      content:
        '때​ 오, 별들을 나는 타는 쌓인 갈라놓는 거리가 얼마나 못하는 가로질러 못하는 바다를 걱정도 모습 홀연히 아름다운 이름자 뚝떼어 너도 박명의 왔을까 우는 올라간다. 무덤 있었다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '15초록노랑 알파카',
        accountname: '@al__12345',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '16',
      content:
        '한 나의 고독은 둘은 그리도 잊지 차츰 시각에 그 눈물 가실 내 경, 노래를 가로질러 둘로 어찌 내 목란배 사람들의 것이다​ 먹이고 불어오는 가실 하나에 생각이다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '16초록초록 알파카',
        accountname: '@al__1',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '17',
      content:
        '이런 자랑처럼 위에 유유히 책상을 까닭입니다. 것을 그리고 밤이 오는 모습 지나고 할 헤는 하나둘 청명한 알리라, 같이 말이 아이들의 고독한 향한 못하는 생을 있다 말했다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '초록색 알파카',
        username: '17초록초록 알파카2',
        accountname: 'al__12',
        intro: '안녕 난 알파카2',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '18',
      content:
        '이국 한마디씩 자랑처럼 헤어져 기억해주오 이렇게 지나고 위에 기억해주오 네가 않은 아니 기억해주오 것을 건너 책상을 그러나 향할 소학교 죽고 것은 육체와 우리를 멀리 가시는 써요.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '3',
        username: '18초록파랑알파카',
        accountname: 'al__123',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '19',
      content:
        '하늘을 붉은 이 먼 모두가 그리고 밟고 것 일로도 청춘이 위에 어찌 하지만 사뿐히 침상에서 바다에서 오, 네가 타는 어린 꽃을 꿈꿀 저편으로 밤 사랑했지 다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '19초록빨강 알파카',
        accountname: '@al__1234',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '20',
      content:
        '때​ 오, 별들을 나는 타는 쌓인 갈라놓는 거리가 얼마나 못하는 가로질러 못하는 바다를 걱정도 모습 홀연히 아름다운 이름자 뚝떼어 너도 박명의 왔을까 우는 올라간다. 무덤 있었다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '20초록노랑 알파카',
        accountname: '@al__12345',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '21',
      content:
        '한 나의 고독은 둘은 그리도 잊지 차츰 시각에 그 눈물 가실 내 경, 노래를 가로질러 둘로 어찌 내 목란배 사람들의 것이다​ 먹이고 불어오는 가실 하나에 생각이다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '21초록초록 알파카',
        accountname: '@al__1',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '22',
      content:
        '이런 자랑처럼 위에 유유히 책상을 까닭입니다. 것을 그리고 밤이 오는 모습 지나고 할 헤는 하나둘 청명한 알리라, 같이 말이 아이들의 고독한 향한 못하는 생을 있다 말했다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '초록색 알파카',
        username: '22초록초록 알파카2',
        accountname: 'al__12',
        intro: '안녕 난 알파카2',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '23',
      content:
        '이국 한마디씩 자랑처럼 헤어져 기억해주오 이렇게 지나고 위에 기억해주오 네가 않은 아니 기억해주오 것을 건너 책상을 그러나 향할 소학교 죽고 것은 육체와 우리를 멀리 가시는 써요.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '3',
        username: '23초록파랑알파카',
        accountname: 'al__123',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '24',
      content:
        '하늘을 붉은 이 먼 모두가 그리고 밟고 것 일로도 청춘이 위에 어찌 하지만 사뿐히 침상에서 바다에서 오, 네가 타는 어린 꽃을 꿈꿀 저편으로 밤 사랑했지 다.',
      image: '/assets/video.png',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '24초록빨강 알파카',
        accountname: '@al__1234',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '25',
      content:
        '때​ 오, 별들을 나는 타는 쌓인 갈라놓는 거리가 얼마나 못하는 가로질러 못하는 바다를 걱정도 모습 홀연히 아름다운 이름자 뚝떼어 너도 박명의 왔을까 우는 올라간다. 무덤 있었다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '25초록노랑 알파카',
        accountname: '@al__12345',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '26',
      content:
        '때​ 오, 별들을 나는 타는 쌓인 갈라놓는 거리가 얼마나 못하는 가로질러 못하는 바다를 걱정도 모습 홀연히 아름다운 이름자 뚝떼어 너도 박명의 왔을까 우는 올라간다. 무덤 있었다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '26초록노랑 알파카',
        accountname: '@al__12345',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '27',
      content:
        '때​ 오, 별들을 나는 타는 쌓인 갈라놓는 거리가 얼마나 못하는 가로질러 못하는 바다를 걱정도 모습 홀연히 아름다운 이름자 뚝떼어 너도 박명의 왔을까 우는 올라간다. 무덤 있었다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '27초록노랑 알파카',
        accountname: '@al__12345',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
    {
      id: '28',
      content:
        '때​ 오, 별들을 나는 타는 쌓인 갈라놓는 거리가 얼마나 못하는 가로질러 못하는 바다를 걱정도 모습 홀연히 아름다운 이름자 뚝떼어 너도 박명의 왔을까 우는 올라간다. 무덤 있었다.',
      image: '',
      createdAt: '2023-06-01',
      updatedAt: '2023-06-01',
      hearted: false,
      heartCount: 12,
      commentCount: 11,
      author: {
        _id: '1',
        username: '28초록노랑 알파카',
        accountname: '@al__12345',
        intro: '안녕 난 알파카',
        image: '',
        isfollow: true,
        following: [],
        follower: [],
        followerCount: 10,
        followingCount: 10,
      },
    },
  ],
};
